### PR TITLE
add request-chan

### PR DESCRIPTION
**Pull request by mpenet**
Adding another flavor of request that feeds a `clojure.core.async/promise-chan` + minor fixes in http.clj

### CODE REVIEW

**Comment by pyr** [comment]
Thanks a lot @mpenet. Things are looking good but beware of buffer accounting which might not be just right for now. We will run load tests before merging to make sure there are no leaks.

**Comment by pyr** [comment]
Also, the client hasn't received much love yet, so let's see where that leaves us.

**Comment by mpenet** [comment]
No worries, I am just playing at this point. I saw the client is lacking in a few areas (redirect support etc), I might send some PRs your way when I get more time. The request/response map part is also screaming for tests (specs?).

**Comment by pyr** [comment]
Yes, I intend to spec around the namespaces, like I did the bootstrap part.
I can't hide my intention is to be roughly on feature parity with jet for the http part in the long run.

**Comment by mpenet** [comment]
Sweet :) 
I did some (hard to fix) mistakes in Jet, and kinda lost interest tbh. I am likely to divert my efforts from jet to net.

**Comment by pyr** [comment]
I was sort of hoping you'd say that. Just tell me when you want direct access to the repo :-)

**Comment by mpenet** [comment]
You can go on with it, thanks:+1: 

I will most likely use PRs tho. I might give a stab at building req/resp specs next.

**Pull request merged**
