### PR TITLE
Disconnect connected clients on shutdown

### PR DESCRIPTION
**Pull request by CRHough**

### CODE REVIEW

**Comment by pyr** [comment]
Hi @CRHough,

Here I would argue for writing a function in bootstrap.clj to fetch the child-group. `shutdown-gracefully!` already exists in bootstrap.clj, so you can use that.

**Comment by CRHough** [comment]
Fair enough.

I didn't notice the function in bootstrap.clj. Thanks for pointing it out.

**Comment by pyr** [comment]
@CRHough I didn't mean for you to close the PR, you can just adapt the code and push again I will squash  when merging.

**Comment by CRHough** [comment]
I'm not entirely sure what that would look like.

I did just notice bootstrap/shutdown-fn. It might be called from tcp/server like this

```(shutdown-fn (channel/channel srv) (.childGroup bs))```

instead of

```(fn [] (-> srv channel/channel ...```

**EDIT:** At first blush it seems to work.

I'll have to test it. Is that more along the lines of what you're thinking though?

**Comment by CRHough** [comment]
@pyr Okay, between this change and the previous tcp/server-bootstrap changes the thing works how I'd expect. This should have been part of the childGroup change.

I'm not sure yet how to get the child group from the server yet as I'm inexperienced with Netty so I can't add that as a function on its own in bootstrap.clj. Once I figure it out I'll make another PR.

**Pull request merged**
