### PR TITLE
fix reflection + bug

### PR DESCRIPTION
**Pull request by mpenet**
Hi, 

It's a first attempt at covering all sites that reflect. 
Hopefully it's all right, I just left the ssl ns, mainly because I ran out of time and varargs are a pain :|

There are a few odditites tho, such as https://github.com/pyr/net/compare/master...mpenet:reflect?expand=1#diff-acd230e76f656aeef49860a6c4329074R106 I couldn't find any ref to such a method for any ABoostrap types. I guess you meant ChannelFuture instead? 
Also on https://github.com/pyr/net/compare/master...mpenet:reflect?expand=1#diff-e35a6f24aca919a45822350f1a8e0d86L254 there was a bug where the getter was used instead of the setter. 

cheers!

### CODE REVIEW

**Comment by pyr** [comment]
I was actually doing reflection fixes in net.ssl today :-)
Thanks **a lot** for this @mpenet :+1: :+1:

**Comment by mpenet** [comment]
you're welcome. There are a few missing pieces but I ll see if I can them get covered later today maybe.

**Comment by pyr** [comment]
It should be all good now, thanks again for the nice nudge and huge work.
I'll try to find a way to make the array of X509Certificates hints look nicer.

**Comment by mpenet** [comment]
FYI I just tried to run `net` against on one of our services, it broke at one of our middlewares that expects the response body of http requests from the server to be input-streams, and was getting a core.async/chan instance. This is expected, since its' working as designed, but maybe it could be useful to provide a few helpers to deal with this kind of things.

**Comment by mpenet** [comment]
In an ideal world, we could imagine having the body decoding (well the whole "initializer") dicted by a middleware, so that could be configurable per handler. Thinking out loud.

**Pull request merged**
